import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  const user = useUser()
  const {data} = api.message.getAll.useQuery()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen bg-zinc-900 flex flex-col items-center">
        <div className="text-zinc-100 p-2">
        {
        !user.isSignedIn && 
          <SignInButton mode="modal">
            <button className="btn">
              Sign in
            </button>
          </SignInButton>
        }
        {
          !!user.isSignedIn &&
          <SignOutButton>
            <button className="btn">
              Sign Out
            </button>
          </SignOutButton>
        }
        </div>
        <section className="relative w-[50%] bg-zinc-200 h-96 overflow-scroll rounded-2xl">
          <div className="absolute flex flex-col gap-8 bottom-10 right-8">
            {data?.map((message) => (
              <div key={message.id} className="p-4 bg-emerald-300 rounded-2xl flex justify-center items-center w-fit text-lg">
                {message.body}
              </div>
            ))}
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
